markdown: kramdown
permalink: /:title.html
url: https://oding-Cx.github.io
lsi: true
rouge: true
safe: true

# presonal config
title: 丁哥的博客
feed: /atom.xml
comments: disqus

author:
  name: 丁哥
  nickname: oding
  email: oding@outlook.com
  gmail: ixxoo.me@gmail.com
  qqmail: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=GnZzcX94f257WmtrNHl1dw
  qqlist: http://list.qq.com/cgi-bin/qf_invite?id=eff06957927177ae5d491bb3c18e4a3c5fc328c95b6ae04f
  site: https://oding-Cx.github.io

seo:
  keyword:
  description:
